version: '2'
services:
  
  # Zookeeper
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  
  # Kafka
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
     - 29093:29093
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
#     - BROKER_ID= 1
#     - LISTENERS= INTERNAL://:9093,EXTERNAL://:29093
#     - ADVERTISED_LISTENERS= INTERNAL://kafka:9093,EXTERNAL://localhost:29093

  # debezium connector
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka

    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

  # Debezium UI
#  dbezium-ui:
#    image: debezium/debezium-ui:${DEBEZIUM_VERSION}
#    container_name: dbezium-UI
#    ports:
#      - 8080:8080
#    environment:
#      - KAFKA_CONNECT_URIS=http://connect:8083
#    links:
#      - connect
#    depends_on:
#      - connect
#      - kafka
#      - zookeeper

  #kafdrop for topic/msg visualization
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx512M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    ports:
      - 9000:9000
    depends_on:
      - kafka
#      - kafka2


#  sqlserver:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    ports:
#     - 1433:1433
#    environment:
#     - ACCEPT_EULA=Y
#     - MSSQL_PID=Standard
#     - SA_PASSWORD=Password!
#     - MSSQL_AGENT_ENABLED=true